[tool.poetry]
name = "dz19-1"
version = "0.1.0"
description = ""
authors = ["Oleg Nanovskiy <oociso@ya.ru>"]
readme = "README.md"
packages = [{include = "dz19"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
